pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/akshay-sakharwade/devops-ci-cd-go-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t go-devops-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:8080 go-devops-app'
            }
        }
    }
}
